<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\**\*.cs"
             Exclude="..\..\src\bin\**;..\..\src\obj\**"
             Link="src\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
